##common properties that can we can override by environments

image:
  registry: docker.io
  repository: 2470/home_task
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: "4000m"  # 4 CPU
    memory: "4Gi"  # 4 Gigabyte
  requests:
    cpu: "1000m"   # 1 CPU
    memory: "512Mi"  # 512 Megabytes

service: 
  name: hello
  externalPort: 5000
  internalPort: 5000
  type: LoadBalancer
  enabled: true

# Release information
release:
  name: my-release

namespace:
  enabled: true
  name: my-app

# serviceAccount:
#   create: true
#   name: my-serviceaccount

# Replica count for the Deployment
replicaCount: 1