apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
  labels: 
    app: {{ .Values.microservice.name }}-{{ .Values.version | default .Chart.AppVersion }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.app }}
    spec:
      containers:
        - name: {{ .Values.service.app }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: http
          readinessProbe:
            httpGet:
              path: /health  
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 30  
            periodSeconds: 10 
            failureThreshold: 3
