apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release.name }}-deployment
  # namespace: {{ .Values.namespace.name }}
  labels: 
    app: {{ .Values.service.name }}-{{ .Values.version | default .Chart.AppVersion }}
    # release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: {{ .Values.service.name }}-container
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
          # image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - containerPort: {{ .Values.service.externalPort }}
        env:
          - name: ENV_VARIABLE_NAME
            value: "Dev"
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}


          #     name: http
          # readinessProbe:
          #   httpGet:
          #     path: /health  
          #     port: {{ .Values.service.externalPort }}
          #   initialDelaySeconds: 60  
          #   periodSeconds: 20 
          #   failureThreshold: 5
