apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release.name }}-deployment
  namespace: {{ .Values.namespace.name }}
  labels: 
    app: {{ .Values.service.name }}-{{ .Values.version | default .Chart.AppVersion }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}  
      containers:
      - name: {{ .Values.service.name }}-container
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.externalPort }}
        env:
          - name: ENV_VARIABLE_NAME
            value: "Dev"
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}