{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.backend.serviceName }}-deployment
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.name }}
  type: {{ .Values.service.type }}
{{- end }}