apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.hosts.backend.serviceName }}
          {{ .Values.hosts.backend.serviceName }}-deployment
        {{ else }}
          default-service
        {{ end }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.name }}
  type: {{ .Values.service.type }}